package main

type Emoji struct {
	Text string `json:"text"`
	Code string `json:"code"`
	Desc string `json:"desc"`
}

var DefaultEmojis = []*Emoji{
	{Text: "🎨", Code: "art", Desc: "结构改进 / 格式化代码"},
	{Text: "⚡️", Code: "zap", Desc: "性能改善"},
	{Text: "🔥", Code: "fire", Desc: "删除代码或者文件"},
	{Text: "🐛", Code: "bug", Desc: "修了一个 BUG"},
	{Text: "🚑", Code: "ambulance", Desc: "重大热修复"},
	{Text: "✨", Code: "sparkles", Desc: "引入新的特性"},
	{Text: "📝", Code: "pencil", Desc: "写文档"},
	{Text: "🚀", Code: "rocket", Desc: "部署相关"},
	{Text: "💄", Code: "lipstick", Desc: "更新界面与样式文件"},
	{Text: "🎉", Code: "tada", Desc: "创世提交"},
	{Text: "🆕", Code: "new", Desc: "引入新功能或新特性"},
	{Text: "✅", Code: "white_check_mark", Desc: "更新测试"},
	{Text: "🔒", Code: "lock", Desc: "修复安全问题"},
	{Text: "🍎", Code: "apple", Desc: "修复在苹果系统上的问题"},
	{Text: "🐧", Code: "penguin", Desc: "修复在 Linux 系统上的问题"},
	{Text: "🏁", Code: "checkered_flag", Desc: "修复在 Windows 系统上的问题"},
	{Text: "🤖", Code: "robot", Desc: "修复在安卓系统上的问题"},
	{Text: "🍏", Code: "green_apple", Desc: "修复在 iOS 系统上的问题"},
	{Text: "🔖", Code: "bookmark", Desc: "发布 / 版本标签"},
	{Text: "🚨", Code: "rotating_light", Desc: "消除 linter 警告"},
	{Text: "🚧", Code: "construction", Desc: "进行中"},
	{Text: "💚", Code: "green_heart", Desc: "修复持续集成构建"},
	{Text: "⬇️", Code: "arrow_down", Desc: "降级依赖"},
	{Text: "⬆️", Code: "arrow_up", Desc: "升级依赖"},
	{Text: "📌", Code: "pushpin", Desc: "固定依赖在特定的版本"},
	{Text: "👷", Code: "construction_worker", Desc: "添加持续集成构建系统"},
	{Text: "📈", Code: "chart_with_upwards_trend", Desc: "添加分析或者跟踪代码"},
	{Text: "♻️", Code: "recycle", Desc: "代码重构"},
	{Text: "🐳", Code: "whale", Desc: "Docker 容器相关"},
	{Text: "➕", Code: "heavy_plus_sign", Desc: "添加依赖"},
	{Text: "➖", Code: "heavy_minus_sign", Desc: "删除依赖"},
	{Text: "🔧", Code: "wrench", Desc: "改变配置文件"},
	{Text: "🌐", Code: "globe_with_meridians", Desc: "国际化与本地化"},
	{Text: "✏️", Code: "pencil2", Desc: "修正拼写错误"},
	{Text: "💩", Code: "poop", Desc: "写需要改进的坏代码"},
	{Text: "⏪", Code: "rewind", Desc: "回滚改动"},
	{Text: "🔀", Code: "twisted_rightwards_arrows", Desc: "合并分支"},
	{Text: "📦", Code: "package", Desc: "更新编译后的文件或者包"},
	{Text: "👽", Code: "alien", Desc: "由于外部 API 变动而更新代码"},
	{Text: "🚚", Code: "truck", Desc: "文件移动或者重命名"},
	{Text: "📄", Code: "page_facing_up", Desc: "添加或者更新许可"},
	{Text: "💥", Code: "boom", Desc: "引入破坏性的改动"},
	{Text: "🍱", Code: "bento", Desc: "添加或者更新静态资源"},
	{Text: "👌", Code: "ok_hand", Desc: "代码审核后更新代码"},
	{Text: "♿️", Code: "wheelchair", Desc: "改进可访问性"},
	{Text: "💡", Code: "bulb", Desc: "给源代码加文档"},
	{Text: "🍻", Code: "beers", Desc: "醉写代码"},
	{Text: "💬", Code: "speech_balloon", Desc: "更新文本和字面"},
	{Text: "🗃", Code: "card_file_box", Desc: "执行数据库相关的改动"},
	{Text: "🔊", Code: "loud_sound", Desc: "添加日志"},
	{Text: "🔇", Code: "mute", Desc: "删除日志"},
	{Text: "👥", Code: "busts_in_silhouette", Desc: "添加贡献者（们）"},
	{Text: "🚸", Code: "children_crossing", Desc: "改进用户体验 / 可用性"},
	{Text: "🏗", Code: "building_construction", Desc: "架构改动"},
	{Text: "📱", Code: "iphone", Desc: "响应性设计相关"},
	{Text: "🤡", Code: "clown_face", Desc: "模拟相关"},
	{Text: "🥚", Code: "egg", Desc: "添加一个彩蛋"},
	{Text: "🙈", Code: "see_no_evil", Desc: "添加或者更新 .gitignore 文件"},
	{Text: "📸", Code: "camera_flash", Desc: "添加或者更新快照"},
	{Text: "⚗", Code: "alembic", Desc: "研究新事物"},
	{Text: "🔍", Code: "mag", Desc: "改进搜索引擎优化"},
	{Text: "☸️", Code: "wheel_of_dharma", Desc: "Kubernetes 相关的工作"},
	{Text: "🏷️", Code: "label", Desc: "添加或者更新类型（如：Flow, TypeScript, Go 等）"},
}
